// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2XEixLCoxoGbp64pG-bhxMKtaiIUSVw',
    appId: '1:558562721234:web:ebf54617278aa44f9d5c0b',
    messagingSenderId: '558562721234',
    projectId: 'bmiapp-83173',
    authDomain: 'bmiapp-83173.firebaseapp.com',
    storageBucket: 'bmiapp-83173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7U3EvBx5d1NhyH-ZRJu2iP7pfJJcBEq8',
    appId: '1:558562721234:android:05214bf1eadc614b9d5c0b',
    messagingSenderId: '558562721234',
    projectId: 'bmiapp-83173',
    storageBucket: 'bmiapp-83173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrzLqsf_bK83dDTZqxFuJiwy3VcP6yYU',
    appId: '1:558562721234:ios:f780f9d8f172852a9d5c0b',
    messagingSenderId: '558562721234',
    projectId: 'bmiapp-83173',
    storageBucket: 'bmiapp-83173.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwrzLqsf_bK83dDTZqxFuJiwy3VcP6yYU',
    appId: '1:558562721234:ios:f780f9d8f172852a9d5c0b',
    messagingSenderId: '558562721234',
    projectId: 'bmiapp-83173',
    storageBucket: 'bmiapp-83173.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2XEixLCoxoGbp64pG-bhxMKtaiIUSVw',
    appId: '1:558562721234:web:c78f1460839ca8249d5c0b',
    messagingSenderId: '558562721234',
    projectId: 'bmiapp-83173',
    authDomain: 'bmiapp-83173.firebaseapp.com',
    storageBucket: 'bmiapp-83173.appspot.com',
  );

}